events {}

http {
    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth-service:3001/;
        }

        location /event/ {
            proxy_pass http://event-service:3002/;
        }
        location /analytics/ {
            proxy_pass http://analytics-service:3003/;
}
    }
}